# -*- coding: utf-8 -*-
"""wine type deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYPxWDBmE0OrCY0ZsG7imf6xN3haiTNn
"""

!pip install streamlit

import numpy as np
import joblib
import streamlit as st

# wine_quality_model.pkl

model = joblib.load('wine_quality_model.pkl')

st.set_page_config(page_title='Wine Quality Classification',layout='centered')
st.title("Wine Quality Classification App")
st.write("predict whether the is **red** or **white** using chemical properties")
fixed_acidity = st.number_input(" value of fixed_acidity",value=None)
volatile_acidity = st.number_input(" value of volatile_acidity",value=None)
citric_acid =st.number_input(" value of citric_acid",value=None)
residual_sugar = st.number_input(" value of residual_sugar",value=None)
chlorides = st.number_input(" value of chlorides ",value=None)
free_sulfur_dioxid =st.number_input(" value of free_sulfur_dioxid ",value=None)
total_sulfur_dioxide =st.number_input(" value of total_sulfur_dioxide",value=None)
density =st.number_input(" value of density",value=None)
pH =st.number_input(" value of pH",value=None)
sulphates =st.number_input(" value of sulphates",value=None)
alcohol = st.number_input(" value of alcohol",value=None)
quality = st.number_input(" value of quality",value=None)

if st.button("Predict"):
  input_data = np.array([[fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxid,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality]])
  predication = model.predict(input_data)
  if predication == 1 :
    st.success("** White wine**")
  else:
    st.error("**Red Wine**")
